import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";

import Header from "components/Header/Header";
import TaskInput from "components/TaskInput/TaskInput";
import RegisteredTasks from "components/RegisteredTasks/RegisteredTasks";
import { ITask } from "components/Task/Task";

const Home: NextPage = () => {
  const [tasks, setTasks] = useState<ITask[]>([]);

  const handleTask = (
    title: string,
    status: boolean,
    deleting: boolean = false
  ) => {
    if (deleting) {
      let updatedTasks = [...tasks].filter((el) => el.title !== title);
      setTasks(updatedTasks);
      return;
    } else if (tasks.find((el) => el.title === title)) {
      const newArr = [...tasks];
      const updatedTasks = newArr.map((task) => {
        if (task.title === title) {
          return { ...task, status: status };
        }
        return task;
      });

      setTasks(updatedTasks);
      return;
    }

    setTasks([...tasks, { title: title, status: status }]);
  };

  return (
    <div>
      <Head>
        <title>TODO App - Venturus Residência React</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <TaskInput register={handleTask} />
      <RegisteredTasks tasks={tasks} update={handleTask} />

      <footer>Giovani Anhesini - 11/17/2021</footer>
    </div>
  );
};

export default Home;
